
logging:
  level:
    root: info
    com:
      car_rental: debug

spring:
  datasource:
    url: jdbc:h2:mem:car_rental
    username: ${H2_DB_USERNAME}
    password: ${H2_DB_PASSWORD}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate